### ISSUE TITLE
cppファイルに足りない箇所有り

### ISSUE THREAD

**Issue by ukaaaai** [nekoshark02/login_tekitou#1]
### string型変数について
11行目に ` string user ; `とありますが、string型の変数を使いたい場合は ` #include<string> `を追加しておくといいです。

### main関数について
main関数を閉じるための ` } `が抜けています。

**Comment by nekoshark02** [comment]
ありがとうございます!
流石先輩だ…
すぐに訂正します!

**Comment by nekoshark02** [comment]
訂正できました!
ご指摘本当にありがとうございました!
